### ISSUE TITLE
Fractional line is shifted downwards when parent container has a fixed height

### ISSUE THREAD

**Issue by michaelniedermayr** [simpleclub/CaTeX#38]
### Describe the bug

If the parent container has a fixed height and a fraction is displayed, the fraction line is moved downwards to bottom of the parent container. However, if the height is not defined, the fraction line is displayed in the correct place.

![Capture](https://user-images.githubusercontent.com/8593661/86244094-b93df780-bba7-11ea-9344-dc6f4897dcac.JPG)

### To Reproduce

Tested with Flutter web and catex 0.0.1
Flutter 1.19.0-4.1.pre • channel beta 
Dart 2.9.0 (build 2.9.0-14.1.beta)

```
Container(
   width: 300,
   height: 100,
   child: CaTeX(r'\frac{2}{3} \cdot \sqrt{2} \cdot \pi')
)
```

**Comment by creativecreatorormaybenot** [comment]
Thank you for the detailed bug report! I think I used the wrong size to position the line, so it is an easy fix 🙂
