### ISSUE TITLE
version solving

### ISSUE THREAD

**Issue by equisbacon** [simpleclub/CaTeX#52]
Could you reduce the 

environment:
   sdk: ">=2.8.4 <3.0.0"

in pubspec.yaml to

environment:
   sdk: ">=2.7.9 <3.0.0"

in order to allow use with older flutter versions?

**Comment by creativecreatorormaybenot** [comment]
We never go above `stable` (see [Dart releases](https://dart.dev/get-dart)). So if you are on Flutter `stable` and run `flutter upgrade`, `catex` will always work.

Is there a need for you to use an even older version?  
If there is a valid reason, we can adjust it 👍🏽

By default, we choose `stable` as it has useful features.

**Comment by equisbacon** [comment]
I had a problem with GlobalKeys in my app and the only way I found to solve it was downgrading to flutter 1.14.6, I tried all new versions from all channels.

**Comment by creativecreatorormaybenot** [comment]
🤔 I am pretty sure that there is a way to solve the problem in newer Flutter versions, maybe you can ask on StackOverflow or open an issue at https://github.com/flutter/flutter/issues.

You see, I would love to help you here - still, it seems like this is not really a problem with the package, but rather with some concrete code of yours 😶  
In the future, we will not upgrade the version constraint of this package immediately, but only when necessary. This way, everyone has time to figure out how to make their app run on at least Flutter `stable`.

I hope I was able to at least answer your concerns in some way → probably sticking with an outdated version of Flutter is not a good solution. Thus, I will close this for now. Let me know if you think this should be reopened 😃
