### ISSUE TITLE
Support for \,

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [simpleclub/CaTeX#59]
## Bug description

`\,` is unable to be rendered.

### To Reproduce

Quite simple: try to render a formula containing `\,` 

## Expected behavior

You should get a nice space between two parts of your formula.

**Comment by creativecreatorormaybenot** [comment]
👍🏽 this fits together with #32 - might split that up later, but for now it seems like one effort.  
Thus, I will add your report to that issue 🙂
