### ISSUE TITLE
Feature Request to overflow the text to next line rather than truncating it

### ISSUE THREAD

**Issue by avi-yadav** [simpleclub/CaTeX#60]
I really appreciate the work which you are doing. This is a great plugin which will be really helpful to a lot of people. 
The current implementation restricts the length of Catex text to the width of the screen. Rest of the text is truncated. There should be some way to overflow this text to next screen. I agree that behaviour is highly undefined in cases of math formulas. But, this will be really helpful in cases where we have a mix of `normal text` and `math formulas` together. Please let me know, if there is already a way to achieve this via some workarounds. I couldn't figure out a way to achieve this.

**Comment by avi-yadav** [comment]
Closing this issue since katex_flutter serves my purpose and has started using CaTex as rendering engine. Thanks.

**Comment by creativecreatorormaybenot** [comment]
@avi-yadav You can use a `SingleChildScrollView` as well 👍🏽
